# Generated by Django 3.0.4 on 2021-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20210131_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=25)),
                ('typeOfOrg', models.CharField(choices=[('Food Bank', 'Food Bank'), ('Grocery Store', 'Grocery Store'), ('Restaurant', 'Restaurant'), ('Distribution Center', 'Distribution Center'), ('Other', 'Other')], default='Food Bank', max_length=25)),
            ],
        ),
    ]
